/* INSERT INTO word (palavra, traducao, letra) VALUES 
('Alone', 'Sozinho', 'A'),
('And', 'E', 'A'),
('Address', 'Endereço', 'A'),
('Also', 'Também', 'A'),
('All', 'Todos', 'A'),
('Allow', 'Permitir', 'A'),
('About', 'Sobre', 'A'),
('After', 'Depois', 'A'),
('Afternoon', 'Tarde', 'A'),
('Any', 'Qualquer', 'A'),
('Anything', 'Qualquer coisa', 'A'),
('Ask', 'Perguntar', 'A'),
('Above', 'Acima', 'A'),
('Always', 'Sempre', 'A'),
('Are', 'São', 'A'),
('Accept', 'Aceitar', 'A'),
('Air', 'Ar', 'A'),
('Author', 'Autor', 'A'),
('Agent', 'Agente', 'A'),
('Authority', 'Autoridade', 'A'),
('Again', 'De Novo', 'A'),
('Age', 'Idade', 'A'),
('Agree', 'Concordar', 'A'),
('Avenue', 'Avenida', 'A'),
('Avoid', 'Evitar', 'A'),
('As', 'Como', 'A'),
('Almost', 'Quase', 'A'),
('Anxiety', 'Ansiedade', 'A'),
('Alright', 'Tudo Bem', 'A'),
('Advance', 'Avançar', 'A'),
('Add', 'Adicionar', 'A'),
('Aesthetic', 'Estética', 'A'),
('Aquatic', 'Aquático', 'A'),
('Answer', 'Resposta/Responder', 'A'),
('Award', 'Prêmio', 'A'),
('Angel', 'Anjo', 'A'),
('Able', 'Capaz', 'A'),
('Area', 'Área', 'A'),
('Arm', 'Braço', 'A'),
('Around', 'Por volta de/Em volta de', 'A'),
('Accountant', 'Contador', 'A'),
('Actor', 'Ator', 'A'),
('Actress', 'Atriz', 'A'),
('Ago', 'Atrás - Tempo', 'A'),
('Airplane', 'Avião', 'A'),
('Another', 'Outro(a)', 'A'),
('Ant', 'Formiga', 'A'),
('Anymore', 'Não mais', 'A'),
('Apartment', 'Apartamento', 'A'),
('Apple', 'Maçã', 'A'),
('April', 'Abril', 'A'),
('Architect', 'Arquiteto', 'A'),
('Arrive', 'Chegar', 'A'),
('Article', 'Artigo', 'A'),
('Artist', 'Artista', 'A'),
('August', 'Agosto', 'A'),
('Abducted', 'Sequestrado', 'A'),
('Ability', 'Capacidade', 'A'),
('Aboute', 'Perto', 'A'),
('Absolutely', 'Absolutamente', 'A'),
('Accomplishes', 'Realiza', 'A'),
('According', 'De acordo', 'A'),
('Aunt', 'Tia', 'A'),
('Available', 'Acessível', 'A'),
('Absent', 'Ausência', 'A'),
('Abyss', 'Abismo', 'A'),
('Accident', 'Acidente', 'A'),
('Accountable', 'Responsável', 'A'),
('Accused', 'Acusado', 'A'),
('Achieve', 'Alcançar', 'A'),
('Acknowledged', 'Reconhecido', 'A'),
('Acquire', 'Adquirir', 'A'),
('Across', 'Através', 'A'),
('Act', 'Ato', 'A'),
('Action', 'Ação', 'A'),
('Activity', 'Atividade', 'A'),
('Actual', 'Real', 'A'),
('Actually', 'Na realidade', 'A'),
('Adjust', 'Ajustar', 'A'),
('Admire', 'Admirar', 'A'),
('Adopt', 'Adotar', 'A'),
('Adult', 'Adulto', 'A'),
('Advantage', 'Vantagem', 'A'),
('Adventure', 'Aventura', 'A'),
('Advice', 'Aviso/Conselho', 'A'),
('Adviser', 'Conselheiro', 'A'),
('Asleep', 'Adormecido', 'A'),
('Advocacy', 'Advocacia', 'A'),
('Affairs', 'Romances', 'A'),
('Affect', 'Afetar', 'A'),
('Afford', 'Proporcionar', 'A'),
('Afraid', 'Com medo', 'A'),
('Afterwards', 'Mais tarde/Em seguida', 'A'),
('Against', 'Contra/Pelo contrário', 'A'),
('Ahead', 'Adiante/À frente', 'A'),
('Aid', 'Ajuda', 'A'),
('Aim', 'Alvo', 'A'),
('Airfare', 'Passagem aérea', 'A'),
('Alcoholics', 'Alcoólatras', 'A'),
('Alive', 'Vivo', 'A'),
('Allies', 'Aliados', 'A'),
('Alligator', 'Jacaré', 'A'),
('Along', 'Ao longo', 'A'),
('Aloud', 'Alto', 'A'),
('Already', 'Já', 'A'),
('Although', 'Apesar de/Embora', 'A'),
('Ambitious', 'Ambicioso', 'A'),
('Among', 'Entre', 'A'),
('Ancestor', 'Antepassado', 'A'),
('Angle', 'Ângulo', 'A'),
('Angry', 'Bravo', 'A'),
('Announce', 'Anunciar', 'A'),
('Annoy', 'Incomodar', 'A'),
('Anybody', 'Ninguém', 'A'),
('Anyone', 'Alguém', 'A'),
('Anyway', 'De qualquer forma', 'A'),
('Anywhere', 'Em qualquer lugar', 'A'),
('Apologise', 'Pedir desculpas', 'A'),
('Apparent', 'Aparente', 'A'),
('Appearance', 'Aparência', 'A'),
('Appropriate', 'Adequado', 'A'),
('Argue', 'Argumentar', 'A'),
('Army', 'Exército', 'A'),
('Arrow', 'Seta', 'A'),
('Art', 'Arte', 'A'),
('Arugula', 'Rúcula', 'A'),
('Ashes', 'Cinzas', 'A'),
('Amazing', 'Incrível', 'A'),
('Awesome', 'Impressionante', 'A'),
('Assessment', 'Avaliação', 'A'),
('Ate', 'Comeu', 'A'),
('Atmosphere', 'Atmosfera', 'A'),
('Attention', 'Atenção', 'A'),
('Attorney', 'Advogado', 'A'),
('Automobile', 'Automóvel', 'A'),
('Awake', 'Acordado', 'A'),
('Awareness', 'Consciência', 'A'),
('Away', 'Longe', 'A'),
('Awful', 'Horrível', 'A'),
('Awkward', 'Desajeitado', 'A'); */

INSERT INTO word (palavra, traducao, letra) VALUES 
('Wait', 'Esperar', 'W'),
('Wake', 'Acordar', 'W'),
('Walk', 'Caminhar', 'W'),
('Wall', 'Parede', 'W'),
('Wallet', 'Carteira', 'W'),
('Warm', 'Quente', 'W'),
('Warning', 'Aviso', 'W'),
('Warrior', 'Guerreiro', 'W'),
('Waste', 'Desperdício', 'W'),
('Watch', 'Assistir', 'W'),
('Water', 'Água', 'W'),
('Wave', 'Onda', 'W'),
('Weak', 'Fraco', 'W'),
('Wealth', 'Riqueza', 'W'),
('Weapon', 'Arma', 'W'),
('Wear', 'Vestir', 'W'),
('Weather', 'Tempo', 'W'),
('Web', 'Teia', 'W'),
('Wedding', 'Casamento', 'W'),
('Week', 'Semana', 'W'),
('Weekend', 'Fim de semana', 'W'),
('Weird', 'Estranho', 'W'),
('Welcome', 'Bem-vindo', 'W'),
('Well', 'Bem', 'W'),
('West', 'Oeste', 'W'),
('Whale', 'Baleia', 'W'),
('What', 'O que', 'W'),
('Whatever', 'Qualquer coisa', 'W'),
('Wheel', 'Roda', 'W'),
('When', 'Quando', 'W'),
('Where', 'Onde', 'W'),
('Whether', 'Se', 'W'),
('Which', 'Qual', 'W'),
('While', 'Enquanto', 'W'),
('Whisper', 'Sussurrar', 'W'),
('White', 'Branco', 'W'),
('Who', 'Quem', 'W'),
('Whole', 'Todo', 'W'),
('Whom', 'A quem', 'W'),
('Why', 'Por que', 'W'),
('Wide', 'Largo', 'W'),
('Wife', 'Esposa', 'W'),
('Wild', 'Selvagem', 'W'),
('Will', 'Vontade', 'W'),
('Win', 'Vencer', 'W'),
('Wind', 'Vento', 'W'),
('Window', 'Janela', 'W'),
('Wine', 'Vinho', 'W'),
('Wing', 'Asa', 'W'),
('Winner', 'Vencedor', 'W'),
('Winter', 'Inverno', 'W'),
('Wire', 'Fio', 'W'),
('Wise', 'Sábio', 'W'),
('Wish', 'Desejar', 'W'),
('With', 'Com', 'W'),
('Within', 'Dentro', 'W'),
('Without', 'Sem', 'W'),
('Witness', 'Testemunha', 'W'),
('Wolf', 'Lobo', 'W'),
('Woman', 'Mulher', 'W'),
('Wonder', 'Maravilha', 'W'),
('Wood', 'Madeira', 'W'),
('Word', 'Palavra', 'W'),
('Work', 'Trabalhar', 'W'),
('Worker', 'Trabalhador', 'W'),
('World', 'Mundo', 'W'),
('Worry', 'Preocupar-se', 'W'),
('Worse', 'Pior', 'W'),
('Worst', 'O pior', 'W'),
('Worth', 'Valor', 'W'),
('Would', 'Gostaria', 'W'),
('Wound', 'Ferida', 'W'),
('Wrap', 'Embrulhar', 'W'),
('Wrist', 'Pulso', 'W'),
('Write', 'Escrever', 'W'),
('Writer', 'Escritor', 'W'),
('Wrong', 'Errado', 'W'),
('Wander', 'Vagar', 'W'),
('Wage', 'Salário', 'W'),
('War', 'Guerra', 'W'),
('Warmth', 'Calor', 'W'),
('Washing', 'Lavagem', 'W'),
('Wasp', 'Vespa', 'W'),
('Weakness', 'Fraqueza', 'W'),
('Wealthy', 'Rico', 'W'),
('Webcam', 'Câmera web', 'W'),
('Website', 'Site', 'W'),
('Wedding ring', 'Aliança', 'W'),
('Weigh', 'Pesar', 'W'),
('Weight', 'Peso', 'W'),
('Weirdness', 'Estranheza', 'W'),
('Welcome mat', 'Capacho', 'W'),
('Welfare', 'Bem-estar', 'W'),
('Well-being', 'Bem-estar', 'W'),
('Westward', 'Em direção ao oeste', 'W'),
('Whack', 'Golpear', 'W'),
('Whale shark', 'Tubarão-baleia', 'W'),
('Wheat', 'Trigo', 'W'),
('Wheelchair', 'Cadeira de rodas', 'W'),
('Whip', 'Chicote', 'W'),
('Whirlwind', 'Furacão', 'W'),
('Whiskey', 'Uísque', 'W'),
('Whistle', 'Apito', 'W'),
('Widen', 'Alargar', 'W'),
('Wilderness', 'Selvageria', 'W'),
('Willing', 'Disposto', 'W'),
('Wilt', 'Murchar', 'W'),
('Windshield', 'Para-brisa', 'W'),
('Wingman', 'Apoiador', 'W'),
('Wipe', 'Limpar', 'W'),
('Wisdom', 'Sabedoria', 'W'),
('Witty', 'Engraçado', 'W'),
('Wobble', 'Oscilar', 'W'),
('Wonderland', 'País das maravilhas', 'W'),
('Wooden', 'De madeira', 'W'),
('Wool', 'Lã', 'W'),
('Workshop', 'Oficina', 'W'),
('Worship', 'Adoração', 'W'),
('Wound care', 'Cuidado com feridas', 'W'),
('Wreck', 'Destruir', 'W'),
('Wrench', 'Chave inglesa', 'W'),
('Wrestle', 'Lutar', 'W'),
('Wristband', 'Pulseira', 'W'),
('Wrongdoing', 'Delito', 'W'),
('Wrought', 'Forjado', 'W'),
('Wry', 'Sarcastico', 'W'),
('Wartime', 'Tempo de guerra', 'W'),
('Washcloth', 'Toalhinha', 'W'),
('Waterfall', 'Cachoeira', 'W'),
('Watershed', 'Divisor de águas', 'W'),
('Waver', 'Vacilar', 'W'),
('Webmaster', 'Webmaster', 'W'),
('Wedge', 'Cunha', 'W'),
('Welfare state', 'Estado de bem-estar', 'W'),
('Wet', 'Molhado', 'W'),
('Wharf', 'Cais', 'W'),
('Whereabouts', 'Paradeiro', 'W'),
('Whimper', 'Choramingar', 'W'),
('Whirlpool', 'Redemoinho', 'W'),
('Whisk', 'Batedor', 'W'),
('Whispering', 'Sussurrando', 'W'),
('Whistleblower', 'Denunciante', 'W'),
('Whiz', 'Perito', 'W'),
('Wholehearted', 'Sincero', 'W'),
('Whoop', 'Grito', 'W'),
('Whopper', 'Mentira', 'W'),
('Widening', 'Ampliação', 'W'),
('Wig', 'Peruca', 'W'),
('Wildflower', 'Flor selvagem', 'W'),
('Wildlife', 'Vida selvagem', 'W'),
('Willingness', 'Disposição', 'W'),
('Willy-nilly', 'De qualquer maneira', 'W'),
('Wilted', 'Murchado', 'W'),
('Windbreaker', 'Corta-vento', 'W'),
('Windmill', 'Moinho de vento', 'W'),
('Windowpane', 'Vidraça', 'W'),
('Windswept', 'Varrido pelo vento', 'W'),
('Wingnut', 'Porca borboleta', 'W'),
('Wink', 'Piscadela', 'W'),
('Winner-takes-all', 'Vencedor leva tudo', 'W'),
('Wintry', 'Invernal', 'W'),
('Wiretap', 'Escuta telefônica', 'W'),
('Wisely', 'Sabiamente', 'W'),
('Wishful', 'Esperançoso', 'W'),
('Withdraw', 'Retirar', 'W'),
('Withdrawal', 'Retirada', 'W'),
('Withhold', 'Reter', 'W'),
('Withstand', 'Resistir', 'W'),
('Witnesses', 'Testemunhas', 'W'),
('Witty remark', 'Comentário espirituoso', 'W'),
('Wizard', 'Mago', 'W'),
('Wobbling', 'Oscilação', 'W'),
('Wolverine', 'Carcaju', 'W'),
('Womb', 'Útero', 'W'),
("Women's" 'rights', 'Direitos das mulheres', 'W'),
('Woodcarving', 'Escultura em madeira', 'W'),
('Woodpecker', 'Pica-pau', 'W'),
('Woolen', 'De lã', 'W'),
('Workaholic', 'Viciado em trabalho', 'W'),
('Workshop leader', 'Líder de oficina', 'W'),
('Worm', 'Verme', 'W'),
('Worry-free', 'Sem preocupações', 'W'),
('Worshipper', 'Adorador', 'W'),
('Worst-case', 'Pior cenário', 'W'),
('Worthy', 'Digno', 'W'),
('Wound healing', 'Cicatrização de feridas', 'W'),
('Wow', 'Uau', 'W'),
('Wrangle', 'Disputa', 'W'),
('Wrinkled', 'Enrugado', 'W'),
("Writer's block", 'Bloqueio de escritor', 'W'),
('Writing desk', 'Escrivaninha', 'W'),
('Wrong turn', 'Caminho errado', 'W'),
('Wrongful', 'Ilegal', 'W'),
('Wrought iron', 'Ferro forjado', 'W'),
('Wry smile', 'Sorriso sarcástico', 'W'),
('Wuthering', 'Tempestuoso', 'W');