INSERT INTO word (palavra, traducao, letra) VALUES 
('Alone', 'Sozinho', 'A'),
('And', 'E', 'A'),
('Address', 'Endereço', 'A'),
('Also', 'Também', 'A'),
('All', 'Todos', 'A'),
('Allow', 'Permitir', 'A'),
('About', 'Sobre', 'A'),
('After', 'Depois', 'A'),
('Afternoon', 'Tarde', 'A'),
('Any', 'Qualquer', 'A'),
('Anything', 'Qualquer coisa', 'A'),
('Ask', 'Perguntar', 'A'),
('Above', 'Acima', 'A'),
('Always', 'Sempre', 'A'),
('Are', 'São', 'A'),
('Accept', 'Aceitar', 'A'),
('Air', 'Ar', 'A'),
('Author', 'Autor', 'A'),
('Agent', 'Agente', 'A'),
('Authority', 'Autoridade', 'A'),
('Again', 'De Novo', 'A'),
('Age', 'Idade', 'A'),
('Agree', 'Concordar', 'A'),
('Avenue', 'Avenida', 'A'),
('Avoid', 'Evitar', 'A'),
('As', 'Como', 'A'),
('Almost', 'Quase', 'A'),
('Anxiety', 'Ansiedade', 'A'),
('Alright', 'Tudo Bem', 'A'),
('Advance', 'Avançar', 'A'),
('Add', 'Adicionar', 'A'),
('Aesthetic', 'Estética', 'A'),
('Aquatic', 'Aquático', 'A'),
('Answer', 'Resposta/Responder', 'A'),
('Award', 'Prêmio', 'A'),
('Angel', 'Anjo', 'A'),
('Able', 'Capaz', 'A'),
('Area', 'Área', 'A'),
('Arm', 'Braço', 'A'),
('Around', 'Por volta de/Em volta de', 'A'),
('Accountant', 'Contador', 'A'),
('Actor', 'Ator', 'A'),
('Actress', 'Atriz', 'A'),
('Ago', 'Atrás - Tempo', 'A'),
('Airplane', 'Avião', 'A'),
('Another', 'Outro(a)', 'A'),
('Ant', 'Formiga', 'A'),
('Anymore', 'Não mais', 'A'),
('Apartment', 'Apartamento', 'A'),
('Apple', 'Maçã', 'A'),
('April', 'Abril', 'A'),
('Architect', 'Arquiteto', 'A'),
('Arrive', 'Chegar', 'A'),
('Article', 'Artigo', 'A'),
('Artist', 'Artista', 'A'),
('August', 'Agosto', 'A'),
('Abducted', 'Sequestrado', 'A'),
('Ability', 'Capacidade', 'A'),
('Aboute', 'Perto', 'A'),
('Absolutely', 'Absolutamente', 'A'),
('Accomplishes', 'Realiza', 'A'),
('According', 'De acordo', 'A'),
('Aunt', 'Tia', 'A'),
('Available', 'Acessível', 'A'),
('Absent', 'Ausência', 'A'),
('Abyss', 'Abismo', 'A'),
('Accident', 'Acidente', 'A'),
('Accountable', 'Responsável', 'A'),
('Accused', 'Acusado', 'A'),
('Achieve', 'Alcançar', 'A'),
('Acknowledged', 'Reconhecido', 'A'),
('Acquire', 'Adquirir', 'A'),
('Across', 'Através', 'A'),
('Act', 'Ato', 'A'),
('Action', 'Ação', 'A'),
('Activity', 'Atividade', 'A'),
('Actual', 'Real', 'A'),
('Actually', 'Na realidade', 'A'),
('Adjust', 'Ajustar', 'A'),
('Admire', 'Admirar', 'A'),
('Horn', 'Buzina', 'H'),
('Adopt', 'Adotar', 'A'),
('Adult', 'Adulto', 'A'),
('Advantage', 'Vantagem', 'A'),
('Adventure', 'Aventura', 'A'),
('Advice', 'Aviso/Conselho', 'A'),
('Adviser', 'Conselheiro', 'A'),
('Asleep', 'Adormecido', 'A'),
('Advocacy', 'Advocacia', 'A'),
('Affairs', 'Romances', 'A'),
('Affect', 'Afetar', 'A'),
('Afford', 'Proporcionar', 'A'),
('Afraid', 'Com medo', 'A'),
('Afterwards', 'Mais tarde/Em seguida', 'A'),
('Against', 'Contra/Pelo contrário', 'A'),
('Ahead', 'Adiante/À frente', 'A'),
('Aid', 'Ajuda', 'A'),
('Aim', 'Alvo', 'A'),
('Airfare', 'Passagem aérea', 'A'),
('Alcoholics', 'Alcoólatras', 'A'),
('Alive', 'Vivo', 'A'),
('Allies', 'Aliados', 'A'),
('Alligator', 'Jacaré', 'A'),
('Along', 'Ao longo', 'A'),
('Aloud', 'Alto', 'A'),
('Already', 'Já', 'A'),
('Although', 'Apesar de/Embora', 'A'),
('Ambitious', 'Ambicioso', 'A'),
('Among', 'Entre', 'A'),
('Ancestor', 'Antepassado', 'A'),
('Angle', 'Ângulo', 'A'),
('Angry', 'Bravo', 'A'),
('Announce', 'Anunciar', 'A'),
('Annoy', 'Incomodar', 'A'),
('Anybody', 'Ninguém', 'A'),
('Anyone', 'Alguém', 'A'),
('Anyway', 'De qualquer forma', 'A'),
('Anywhere', 'Em qualquer lugar', 'A'),
('Apologise', 'Pedir desculpas', 'A'),
('Apparent', 'Aparente', 'A'),
('Appearance', 'Aparência', 'A'),
('Appropriate', 'Adequado', 'A'),
('Argue', 'Argumentar', 'A'),
('Army', 'Exército', 'A'),
('Arrow', 'Seta', 'A'),
('Art', 'Arte', 'A'),
('Arugula', 'Rúcula', 'A'),
('Ashes', 'Cinzas', 'A'),
('Amazing', 'Incrível', 'A'),
('Awesome', 'Impressionante', 'A'),
('Assessment', 'Avaliação', 'A'),
('Ate', 'Comeu', 'A'),
('Atmosphere', 'Atmosfera', 'A'),
('Attention', 'Atenção', 'A'),
('Attorney', 'Advogado', 'A'),
('Automobile', 'Automóvel', 'A'),
('Awake', 'Acordado', 'A'),
('Awareness', 'Consciência', 'A'),
('Away', 'Longe', 'A'),
('Awful', 'Horrível', 'A'),
('Awkward', 'Desajeitado', 'A');